version: 2.1

orbs:
  python: rdgozum/python@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

executors:
  ci-base:
    docker:
      - image: cimg/base:2020.01

# Pipeline Parameters
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false

# yaml anchor filters
integration_filter: &integration_filter
  filters:
    branches:
      only:
        - develop
        - main

main_filter: &main_filter
  filters:
    branches:
      only:
        - main

workflows:
  version: 2
  build_unit-test_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack

      - orb-tools/publish-dev:
          orb-name: rdgozum/python
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_publish-prod:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Integration Test for linters
      - python/flake8:
          src: src/python
          <<: *integration_filter

      - python/pylint:
          src: src/python
          <<: *integration_filter

      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: rdgozum/python
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: "62:e3:c9:56:92:9d:f3:45:4a:db:49:ed:fc:97:3b:a6"
          requires:
            - python/flake8
          <<: *main_filter
