description: >
    The docker container default for python.
docker:
    - image: cimg/python:<< parameters.version >>
parameters:
    version:
        default: 3.9.0
        description: Python version for executor
        type: string
